version: "3.9"

services:
  broker:
    container_name: broker-logstash
    image: solace/solace-pubsub-standard:latest
    shm_size: 1g
    ulimits:
      core: 1
      nofile:
        soft: 2448
        hard: 6592
    ports:
      # Solace CLI SSH/SFTP
      - 2222:2222
      #Web transport
      - "8008:8008"
      #Web transport over TLS
      - "443:443"
      #MQTT Default VPN
      - 1883:1883
      #AMQP Default VPN over TLS
      - "5671:5671"
      #AMQP Default VPN
      - "5672:5672"
      #MQTT Default VPN over WebSockets
      - 8000:8000
      #MQTT Default VPN over WebSockets / TLS
      - "8443:8443"
      #MQTT Default VPN over TLS
      - "8883:8883"
      #SEMP / PubSub+ Manager
      - "8080:8080"
      #SEMP / PubSub+ Manager over TLS
      - "1943:1943"
      #REST Default VPN
      - "9000:9000"
      #REST Default VPN over TLS
      - "9443:9443"
      #SMF
      - "44444:55555"
      #SMF Compressed
      - "55003:55003"
      #SMF over TLS
      - "55443:55443"
      # Health Check
      - "5550:5550"
    environment:
      - username_admin_globalaccesslevel=admin
      - username_admin_password=admin

  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:8.1.0
    ports:
      - 51420:51420
      - 51421:51421
      - 51422:51422
    volumes:
      - "./config/logstash.yml:/usr/share/logstash/config/logstash.yml"
      - "./pipeline/:/usr/share/logstash/pipeline/"
      - "./tmp:/tmp"
